include: package:very_good_analysis/analysis_options.7.0.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - lib/generated_plugin_registrant.dart

linter:
  rules:
    public_member_api_docs: false
