name: entries_api
description: The interface and models for an API providing access to entries.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cryptography:
    path: ../cryptography
  equatable: ^2.0.7
  meta: ^1.15.0
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
